name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for docs
        run: |
          cd harmony-docs
          npm ci

      - name: Build docs
        run: |
          cd harmony-docs
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: harmony-docs/out # Next.js static export output folder
          branch: gh-pages # The branch the action should deploy to
